// Generated by gencpp from file tiny_msgs/tinyVector.msg
// DO NOT EDIT!


#ifndef TINY_MSGS_MESSAGE_TINYVECTOR_H
#define TINY_MSGS_MESSAGE_TINYVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiny_msgs
{
template <class ContainerAllocator>
struct tinyVector_
{
  typedef tinyVector_<ContainerAllocator> Type;

  tinyVector_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  tinyVector_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::tiny_msgs::tinyVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiny_msgs::tinyVector_<ContainerAllocator> const> ConstPtr;

}; // struct tinyVector_

typedef ::tiny_msgs::tinyVector_<std::allocator<void> > tinyVector;

typedef boost::shared_ptr< ::tiny_msgs::tinyVector > tinyVectorPtr;
typedef boost::shared_ptr< ::tiny_msgs::tinyVector const> tinyVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiny_msgs::tinyVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiny_msgs::tinyVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiny_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiny_msgs': ['/home/ubuntu/catkin_ws/src/tiny_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiny_msgs::tinyVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiny_msgs::tinyVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiny_msgs::tinyVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiny_msgs::tinyVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiny_msgs::tinyVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiny_msgs::tinyVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiny_msgs::tinyVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85729383565f7e059d4a213b3db1317b";
  }

  static const char* value(const ::tiny_msgs::tinyVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85729383565f7e05ULL;
  static const uint64_t static_value2 = 0x9d4a213b3db1317bULL;
};

template<class ContainerAllocator>
struct DataType< ::tiny_msgs::tinyVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiny_msgs/tinyVector";
  }

  static const char* value(const ::tiny_msgs::tinyVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiny_msgs::tinyVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A Tiny Vector\n\
\n\
int16 x\n\
int16 y\n\
int16 z\n\
";
  }

  static const char* value(const ::tiny_msgs::tinyVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiny_msgs::tinyVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tinyVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiny_msgs::tinyVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiny_msgs::tinyVector_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TINY_MSGS_MESSAGE_TINYVECTOR_H
